# Significancia estadística con OLS

In [16]:
# Cargar librerías

import pandas as pd
import numpy as np
import statsmodels.api as sm

In [17]:
# Configuración

ruta_archivo = "Base_final_narino_cundinamarca.csv"
df = pd.read_csv(ruta_archivo, encoding="utf-8-sig")

In [18]:
# Definir variable objetivo y variables candidatas

target = "Rendimiento"
columna_tiempo = "Año"

variables_numericas = [
    'Precipitación acumulada anual (mm/año)',
    'Temperatura media anual (°C)',
    'Máximo de la temperatura media mensual (°C)',
    'Mínimo de la temperatura media mensual (°C)',
    'Humedad relativa media anual (%)',
    'Radiación solar acumulada anual (MJ/m²/año)',
    'Humedad volumétrica media anual del suelo capa 1 (m³/m³)',
    'Humedad volumétrica media anual del suelo capa 2 (m³/m³)',
    'Evaporación potencial acumulada anual (mm/año)',
    'SPI1_floracion',
    'SPI1_llenado',
    'altitud_media_m',
    'Rendimiento_lag1',
    'Rendimiento_rolling3',
]

variables_categoricas = [
    "Departamento",
    "Municipio"
]
variables_modelo = variables_numericas + variables_categoricas

In [19]:
# Crear base para OLS

columnas_ols = variables_modelo + [target, columna_tiempo]

df_ols = df[columnas_ols].copy()

for col in variables_numericas + [target]:
    df_ols[col] = pd.to_numeric(df_ols[col], errors="coerce")

for col in variables_categoricas:
    df_ols[col] = df_ols[col].astype("category")

df_ols = df_ols.dropna()

df_ols = df_ols.sort_values(columna_tiempo).reset_index(drop=True)

print("Tamaño base OLS:", df_ols.shape)

Tamaño base OLS: (1481, 18)

In [20]:
# Split temporal
anio_corte = int(df_ols[columna_tiempo].quantile(0.80))

df_ols_train = df_ols[df_ols[columna_tiempo] <= anio_corte].copy()
df_ols_test = df_ols[df_ols[columna_tiempo] > anio_corte].copy()

print("Año de corte:", anio_corte)
print("Train:", df_ols_train.shape)
print("Test:", df_ols_test.shape)

Año de corte: 2021
Train: (1212, 18)
Test: (269, 18)

In [21]:
# Crear variables dummy para Departamento y Municipio
X_train_ols = pd.get_dummies(
    df_ols_train[variables_modelo],
    columns=variables_categoricas,
    drop_first=True
)

X_test_ols = pd.get_dummies(
    df_ols_test[variables_modelo],
    columns=variables_categoricas,
    drop_first=True
)

y_train_ols = df_ols_train[target].astype(float)
y_test_ols = df_ols_test[target].astype(float)

X_train_ols, X_test_ols = X_train_ols.align(
    X_test_ols,
    join="left",
    axis=1,
    fill_value=0
)

X_train_ols = X_train_ols.astype(float)
X_test_ols = X_test_ols.astype(float)

X_train_ols = sm.add_constant(X_train_ols)
X_test_ols = sm.add_constant(X_test_ols, has_constant="add")

In [22]:
# Entrenar modelo OLS

modelo_ols = sm.OLS(y_train_ols, X_train_ols).fit()

print(modelo_ols.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Rendimiento   R-squared:                       0.504
Model:                            OLS   Adj. R-squared:                  0.458
Method:                 Least Squares   F-statistic:                     10.84
Date:                Sun, 03 May 2026   Prob (F-statistic):          6.50e-110
Time:                        16:26:19   Log-Likelihood:                 254.73
No. Observations:                1212   AIC:                            -299.5
Df Residuals:                    1107   BIC:                             236.1
Df Model:                         104
Covariance Type:            nonrobust
============================================================================================================================
                                                               coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------------------------
const                                                       -2.0722      1.220     -1.698      0.090      -4.467       0.322
Precipitación acumulada anual (mm/año)                   -2.571e-05   1.67e-05     -1.539      0.124   -5.85e-05    7.07e-06
Temperatura media anual (°C)                                 0.1654      0.043      3.857      0.000       0.081       0.250
Máximo de la temperatura media mensual (°C)                 -0.0328      0.018     -1.789      0.074      -0.069       0.003
Mínimo de la temperatura media mensual (°C)                  0.0632      0.030      2.141      0.032       0.005       0.121
Humedad relativa media anual (%)                            -0.0050      0.007     -0.679      0.497      -0.020       0.010
Radiación solar acumulada anual (MJ/m²/año)                 -0.0002   6.57e-05     -2.958      0.003      -0.000   -6.54e-05
Humedad volumétrica media anual del suelo capa 1 (m³/m³)   -13.2114      3.857     -3.425      0.001     -20.779      -5.643
Humedad volumétrica media anual del suelo capa 2 (m³/m³)    11.4471      3.466      3.303      0.001       4.647      18.247
Evaporación potencial acumulada anual (mm/año)           -8.785e-05   5.55e-05     -1.584      0.114      -0.000     2.1e-05
SPI1_floracion                                               0.0219      0.022      1.008      0.314      -0.021       0.065
SPI1_llenado                                                -0.0129      0.013     -1.018      0.309      -0.038       0.012
altitud_media_m                                              0.0010      0.000      7.011      0.000       0.001       0.001
Rendimiento_lag1                                             0.4688      0.039     11.961      0.000       0.392       0.546
Rendimiento_rolling3                                        -0.0133      0.048     -0.276      0.782      -0.108       0.081
Departamento_NARINO                                          0.1919      0.031      6.173      0.000       0.131       0.253
Municipio_ANOLAIMA                                          -0.3173      0.080     -3.972      0.000      -0.474      -0.161
Municipio_APULO                                             -0.2288      0.093     -2.447      0.015      -0.412      -0.045
Municipio_ARBELAEZ                                           0.0590      0.086      0.688      0.491      -0.109       0.227
Municipio_ARBOLEDA                                           0.3594      0.112      3.206      0.001       0.139       0.579
Municipio_BELTRAN                                           -0.0123      0.165     -0.075      0.941      -0.337       0.312
Municipio_BUESACO                                            0.0999      0.070      1.423      0.155      -0.038       0.238
Municipio_CABRERA                                           -0.2300      0.110     -2.100      0.036      -0.445      -0.015
Municipio_CACHIPAY                                          -0.4663      0.111     -4.193      0.000      -0.685      -0.248
Municipio_CAPARRAPI                                          0.3129      0.257      1.218      0.223      -0.191       0.817
Municipio_CAQUEZA                                            0.4939      0.118      4.197      0.000       0.263       0.725
Municipio_CHACHAGUI                                         -0.4009      0.099     -4.065      0.000      -0.594      -0.207
Municipio_CHAGUANI                                          -0.0547      0.112     -0.487      0.627      -0.275       0.166
Municipio_CHOACHI                                            0.2471      0.114      2.167      0.030       0.023       0.471
Municipio_CONSACA                                            0.2914      0.091      3.208      0.001       0.113       0.470
Municipio_CUMBAL                                            -0.5593      0.154     -3.633      0.000      -0.861      -0.257
Municipio_CUMBITARA                                          0.6371      0.102      6.217      0.000       0.436       0.838
Municipio_EL COLEGIO                                        -0.2033      0.081     -2.507      0.012      -0.362      -0.044
Municipio_EL PENOL                                           0.0847      0.095      0.887      0.375      -0.103       0.272
Municipio_EL PENON                                           0.2809      0.120      2.347      0.019       0.046       0.516
Municipio_EL ROSARIO                                        -0.0040      0.117     -0.035      0.972      -0.233       0.225
Municipio_EL TAMBO                                          -0.2377      0.072     -3.315      0.001      -0.378      -0.097
Municipio_FOMEQUE                                           -0.1106      0.072     -1.529      0.127      -0.252       0.031
Municipio_FOSCA                                              0.3272      0.109      2.996      0.003       0.113       0.541
Municipio_FUNES                                             -0.0787      0.073     -1.082      0.279      -0.221       0.064
Municipio_FUSAGASUGA                                         0.2522      0.097      2.611      0.009       0.063       0.442
Municipio_GACHALA                                            0.0999      0.067      1.484      0.138      -0.032       0.232
Municipio_GACHETA                                            0.0409      0.070      0.581      0.561      -0.097       0.179
Municipio_GAMA                                               0.1798      0.088      2.036      0.042       0.007       0.353
Municipio_GUADUAS                                           -0.0304      0.138     -0.220      0.826      -0.302       0.241
Municipio_GUAITARILLA                                       -0.3574      0.088     -4.052      0.000      -0.530      -0.184
Municipio_GUAYABAL DE SIQUIMA                               -0.0768      0.078     -0.987      0.324      -0.230       0.076
Municipio_GUAYABETAL                                         0.3692      0.093      3.987      0.000       0.187       0.551
Municipio_GUTIERREZ                                          0.1842      0.108      1.713      0.087      -0.027       0.395
Municipio_ILES                                              -0.0848      0.112     -0.756      0.450      -0.305       0.135
Municipio_IMUES                                             -0.0618      0.093     -0.661      0.508      -0.245       0.122
Municipio_IPIALES                                            0.0654      0.165      0.397      0.692      -0.258       0.389
Municipio_JERUSALEN                                         -0.2332      0.120     -1.951      0.051      -0.468       0.001
Municipio_JUNIN                                              0.3566      0.090      3.982      0.000       0.181       0.532
Municipio_LA CRUZ                                           -0.1789      0.090     -1.989      0.047      -0.355      -0.002
Municipio_LA FLORIDA                                         0.0606      0.075      0.811      0.418      -0.086       0.207
Municipio_LA LLANADA                                         0.0678      0.101      0.673      0.501      -0.130       0.265
Municipio_LA MESA                                           -0.0376      0.093     -0.406      0.685      -0.220       0.144
Municipio_LA PALMA                                           0.3341      0.143      2.329      0.020       0.053       0.616
Municipio_LA PENA                                            0.1530      0.131      1.170      0.242      -0.104       0.410
Municipio_LA UNION                                           0.5084      0.112      4.531      0.000       0.288       0.729
Municipio_LEIVA                                              0.1603      0.121      1.322      0.186      -0.078       0.398
Municipio_LINARES                                            0.1099      0.070      1.567      0.117      -0.028       0.247
Municipio_LOS ANDES                                         -0.0903      0.093     -0.967      0.334      -0.273       0.093
Municipio_MACHETA                                            0.3817      0.088      4.340      0.000       0.209       0.554
Municipio_MALLAMA                                           -0.1214      0.084     -1.450      0.147      -0.286       0.043
Municipio_MEDINA                                             0.1677      0.225      0.747      0.455      -0.273       0.608
Municipio_NILO                                               0.2059      0.098      2.095      0.036       0.013       0.399
Municipio_NOCAIMA                                           -0.0753      0.140     -0.539      0.590      -0.349       0.199
Municipio_PACHO                                              0.9593      0.151      6.347      0.000       0.663       1.256
Municipio_PAIME                                              0.3657      0.138      2.651      0.008       0.095       0.636
Municipio_PANDI                                              0.1013      0.139      0.728      0.467      -0.172       0.374
Municipio_PARATEBUENO                                        0.4936      0.329      1.498      0.134      -0.153       1.140
Municipio_PASCA                                             -0.3474      0.094     -3.678      0.000      -0.533      -0.162
Municipio_PASTO                                              0.0066      0.098      0.068      0.946      -0.185       0.199
Municipio_POLICARPA                                         -0.0729      0.099     -0.739      0.460      -0.266       0.120
Municipio_PROVIDENCIA                                       -0.1417      0.081     -1.739      0.082      -0.302       0.018
Municipio_PULI                                              -0.1385      0.123     -1.128      0.260      -0.379       0.102
Municipio_QUEBRADANEGRA                                     -0.2845      0.106     -2.679      0.007      -0.493      -0.076
Municipio_QUETAME                                            0.1210      0.131      0.925      0.355      -0.136       0.378
Municipio_RICAURTE                                          -0.0057      0.119     -0.048      0.962      -0.239       0.227
Municipio_SAMANIEGO                                         -0.0410      0.076     -0.539      0.590      -0.190       0.108
Municipio_SAN BERNARDO                                      -0.3227      0.135     -2.388      0.017      -0.588      -0.058
Municipio_SAN CAYETANO                                       0.2958      0.078      3.807      0.000       0.143       0.448
Municipio_SAN FRANCISCO                                      0.0591      0.065      0.903      0.367      -0.069       0.187
Municipio_SAN JUAN DE RIOSECO                               -0.0089      0.122     -0.073      0.942      -0.249       0.231
Municipio_SAN LORENZO                                        0.2651      0.086      3.075      0.002       0.096       0.434
Municipio_SAN PABLO                                         -0.1530      0.083     -1.853      0.064      -0.315       0.009
Municipio_SANDONA                                           -0.0408      0.067     -0.613      0.540      -0.171       0.090
Municipio_SANTACRUZ                                          0.1427      0.066      2.174      0.030       0.014       0.271
Municipio_SASAIMA                                            0.1601      0.083      1.940      0.053      -0.002       0.322
Municipio_SILVANIA                                          -0.6388      0.110     -5.812      0.000      -0.854      -0.423
Municipio_SUPATA                                             0.3853      0.105      3.655      0.000       0.178       0.592
Municipio_TAMINANGO                                          0.3675      0.121      3.048      0.002       0.131       0.604
Municipio_TANGUA                                            -0.2470      0.102     -2.426      0.015      -0.447      -0.047
Municipio_TIBACUY                                           -0.3796      0.140     -2.715      0.007      -0.654      -0.105
Municipio_TIBIRITA                                           0.2389      0.127      1.878      0.061      -0.011       0.488
Municipio_TOCAIMA                                           -0.0391      0.086     -0.453      0.651      -0.209       0.130
Municipio_TUQUERRES                                         -0.1577      0.122     -1.297      0.195      -0.396       0.081
Municipio_UBALA                                              0.2878      0.120      2.407      0.016       0.053       0.522
Municipio_UBAQUE                                            -0.0087      0.084     -0.104      0.917      -0.173       0.155
Municipio_VERGARA                                            0.2080      0.115      1.814      0.070      -0.017       0.433
Municipio_VILLAGOMEZ                                         0.2304      0.104      2.206      0.028       0.026       0.435
Municipio_VILLETA                                            0.0694      0.096      0.723      0.470      -0.119       0.258
Municipio_VIOTA                                              0.1371      0.077      1.785      0.074      -0.014       0.288
Municipio_YACOPI                                             0.5460      0.275      1.986      0.047       0.006       1.085
Municipio_ZIPACON                                           -0.5946      0.085     -6.986      0.000      -0.762      -0.428
==============================================================================
Omnibus:                       71.534   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              270.562
Skew:                           0.101   Prob(JB):                     1.77e-59
Kurtosis:                       5.306   Cond. No.                     3.94e+19
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.98e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [23]:
# Tabla de significancia estadística

tabla_significancia = pd.DataFrame({
    "variable": modelo_ols.params.index,
    "coeficiente": modelo_ols.params.values,
    "p_value": modelo_ols.pvalues.values
})

tabla_significancia = tabla_significancia[
    tabla_significancia["variable"] != "const"
].copy()

tabla_significancia["significativa_10%"] = tabla_significancia["p_value"] < 0.10
tabla_significancia["significativa_5%"] = tabla_significancia["p_value"] < 0.05
tabla_significancia["significativa_1%"] = tabla_significancia["p_value"] < 0.01

tabla_significancia = tabla_significancia.sort_values(
    "p_value"
).reset_index(drop=True)

tabla_significancia.round(6)

,variable,coeficiente,p_value,significativa_10%,significativa_5%,significativa_1%
0,Rendimiento_lag1,0.468799,0.000000,True,True,True
1,altitud_media_m,0.001025,0.000000,True,True,True
2,Municipio_ZIPACON,-0.594559,0.000000,True,True,True
3,Municipio_PACHO,0.959342,0.000000,True,True,True
4,Municipio_CUMBITARA,0.637077,0.000000,True,True,True
...,...,...,...,...,...,...
101,Municipio_BELTRAN,-0.012349,0.940512,False,False,False
102,Municipio_SAN JUAN DE RIOSECO,-0.008922,0.941886,False,False,False
103,Municipio_PASTO,0.006648,0.945888,False,False,False
104,Municipio_RICAURTE,-0.005713,0.961638,False,False,False
105,Municipio_EL ROSARIO,-0.004044,0.972357,False,False,False

In [24]:

tabla_significancia_numericas = tabla_significancia[
    tabla_significancia["variable"].isin(variables_numericas)
].copy()

tabla_significancia_numericas.round(6)

,variable,coeficiente,p_value,significativa_10%,significativa_5%,significativa_1%
0,Rendimiento_lag1,0.468799,0.000000,True,True,True
1,altitud_media_m,0.001025,0.000000,True,True,True
16,Temperatura media anual (°C),0.165417,0.000121,True,True,True
21,Humedad volumétrica media anual del suelo capa...,-13.211362,0.000637,True,True,True
23,Humedad volumétrica media anual del suelo capa...,11.447121,0.000987,True,True,True
29,Radiación solar acumulada anual (MJ/m²/año),-0.000194,0.003163,True,True,True
44,Mínimo de la temperatura media mensual (°C),0.063232,0.032486,True,True,False
55,Máximo de la temperatura media mensual (°C),-0.032833,0.073968,True,False,False
59,Evaporación potencial acumulada anual (mm/año),-0.000088,0.113510,False,False,False
61,Precipitación acumulada anual (mm/año),-0.000026,0.124122,False,False,False
73,SPI1_llenado,-0.012934,0.308964,False,False,False
74,SPI1_floracion,0.021908,0.313841,False,False,False
87,Humedad relativa media anual (%),-0.005043,0.497396,False,False,False
98,Rendimiento_rolling3,-0.013311,0.782414,False,False,False

In [25]:
# 10. Evaluar OLS en test

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

y_pred_train_ols = modelo_ols.predict(X_train_ols)
y_pred_test_ols = modelo_ols.predict(X_test_ols)

rmse_train_ols = mean_squared_error(y_train_ols, y_pred_train_ols) ** 0.5
rmse_test_ols = mean_squared_error(y_test_ols, y_pred_test_ols) ** 0.5

mae_train_ols = mean_absolute_error(y_train_ols, y_pred_train_ols)
mae_test_ols = mean_absolute_error(y_test_ols, y_pred_test_ols)

r2_train_ols = r2_score(y_train_ols, y_pred_train_ols)
r2_test_ols = r2_score(y_test_ols, y_pred_test_ols)

print("RMSE train OLS:", rmse_train_ols)
print("RMSE test OLS:", rmse_test_ols)
print("MAE train OLS:", mae_train_ols)
print("MAE test OLS:", mae_test_ols)
print("R2 train OLS:", r2_train_ols)
print("R2 test OLS:", r2_test_ols)

RMSE train OLS: 0.19610448289987067
RMSE test OLS: 0.3017483339336456
MAE train OLS: 0.1414017050766284
MAE test OLS: 0.22613972504073931
R2 train OLS: 0.5044975720047629
R2 test OLS: 0.211579207820225

In [26]:
# Tabla final

tabla_justificacion_ols = tabla_significancia_numericas.copy()

tabla_justificacion_ols["decision"] = np.where(
    tabla_justificacion_ols["p_value"] < 0.10,
    "Seleccionada por significancia estadística",
    "Revisar con criterio técnico"
)

tabla_justificacion_ols = tabla_justificacion_ols.sort_values(
    "p_value"
).reset_index(drop=True)

tabla_justificacion_ols.round(6)

,variable,coeficiente,p_value,significativa_10%,significativa_5%,significativa_1%,decision
0,Rendimiento_lag1,0.468799,0.000000,True,True,True,Seleccionada por significancia estadística
1,altitud_media_m,0.001025,0.000000,True,True,True,Seleccionada por significancia estadística
2,Temperatura media anual (°C),0.165417,0.000121,True,True,True,Seleccionada por significancia estadística
3,Humedad volumétrica media anual del suelo capa...,-13.211362,0.000637,True,True,True,Seleccionada por significancia estadística
4,Humedad volumétrica media anual del suelo capa...,11.447121,0.000987,True,True,True,Seleccionada por significancia estadística
5,Radiación solar acumulada anual (MJ/m²/año),-0.000194,0.003163,True,True,True,Seleccionada por significancia estadística
6,Mínimo de la temperatura media mensual (°C),0.063232,0.032486,True,True,False,Seleccionada por significancia estadística
7,Máximo de la temperatura media mensual (°C),-0.032833,0.073968,True,False,False,Seleccionada por significancia estadística
8,Evaporación potencial acumulada anual (mm/año),-0.000088,0.113510,False,False,False,Revisar con criterio técnico
9,Precipitación acumulada anual (mm/año),-0.000026,0.124122,False,False,False,Revisar con criterio técnico
10,SPI1_llenado,-0.012934,0.308964,False,False,False,Revisar con criterio técnico
11,SPI1_floracion,0.021908,0.313841,False,False,False,Revisar con criterio técnico
12,Humedad relativa media anual (%),-0.005043,0.497396,False,False,False,Revisar con criterio técnico
13,Rendimiento_rolling3,-0.013311,0.782414,False,False,False,Revisar con criterio técnico